INSERT INTO tech_catalog (name, category) VALUES
    -- FRONTEND
    ('React',          'FRONTEND'),
    ('Vue.js',         'FRONTEND'),
    ('Angular',        'FRONTEND'),
    ('Next.js',        'FRONTEND'),
    ('Nuxt.js',        'FRONTEND'),
    ('Svelte',         'FRONTEND'),
    ('SvelteKit',      'FRONTEND'),
    ('Remix',          'FRONTEND'),
    ('Astro',          'FRONTEND'),
    ('Vite',           'FRONTEND'),
    ('Tailwind CSS',   'FRONTEND'),
    ('Bootstrap',      'FRONTEND'),
    ('Material UI',    'FRONTEND'),
    ('Chakra UI',      'FRONTEND'),
    -- BACKEND
    ('Spring Boot',    'BACKEND'),
    ('Spring Security','BACKEND'),
    ('Spring Data JPA','BACKEND'),
    ('Node.js',        'BACKEND'),
    ('Express',        'BACKEND'),
    ('NestJS',         'BACKEND'),
    ('Django',         'BACKEND'),
    ('FastAPI',        'BACKEND'),
    ('Flask',          'BACKEND'),
    ('Laravel',        'BACKEND'),
    ('Ruby on Rails',  'BACKEND'),
    ('ASP.NET Core',   'BACKEND'),
    ('Quarkus',        'BACKEND'),
    -- DATABASE
    ('PostgreSQL',     'DATABASE'),
    ('MySQL',          'DATABASE'),
    ('MongoDB',        'DATABASE'),
    ('Redis',          'DATABASE'),
    ('SQLite',         'DATABASE'),
    ('Elasticsearch',  'DATABASE'),
    ('Supabase',       'DATABASE'),
    ('Firebase Firestore','DATABASE'),
    -- DEVOPS
    ('Docker',         'DEVOPS'),
    ('Kubernetes',     'DEVOPS'),
    ('GitHub Actions', 'DEVOPS'),
    ('GitLab CI',      'DEVOPS'),
    ('AWS',            'DEVOPS'),
    ('GCP',            'DEVOPS'),
    ('Azure',          'DEVOPS'),
    ('Vercel',         'DEVOPS'),
    ('Netlify',        'DEVOPS'),
    ('Railway',        'DEVOPS'),
    ('Terraform',      'DEVOPS'),
    ('Nginx',          'DEVOPS'),
    -- MOBILE
    ('React Native',   'MOBILE'),
    ('Flutter',        'MOBILE'),
    ('Android',        'MOBILE'),
    ('iOS Swift',      'MOBILE'),
    ('Kotlin',         'MOBILE'),
    -- OTHER
    ('TypeScript',     'OTHER'),
    ('JavaScript',     'OTHER'),
    ('Python',         'OTHER'),
    ('Java',           'OTHER'),
    ('Go',             'OTHER'),
    ('Rust',           'OTHER'),
    ('Git',            'OTHER'),
    ('Figma',          'OTHER'),
    ('Notion',         'OTHER'),
    ('Postman',        'OTHER'),
    ('Swagger',        'OTHER');
